# Generated by Django 4.2.1 on 2023-05-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=15)),
                ('end_time', models.CharField(max_length=15)),
            ],
        ),
    ]
