# Generated by Django 4.2.1 on 2023-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_subtitledata_modified_time_subtitledata_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubtitleData',
            new_name='SubtitleDataModel',
        ),
    ]
