# Generated by Django 4.2.1 on 2023-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_subtitledata_subtitledatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitledatamodel',
            name='SubtitleID',
            field=models.CharField(default='f7115982-f4cd-11ed-b839-217e1eb0cb07', max_length=36),
        ),
    ]
