# Generated by Django 4.2.1 on 2023-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_subtitledatamodel_subtitleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subtitledatamodel',
            name='SubtitleID',
            field=models.CharField(default='5262786c-f56d-11ed-b839-217e1eb0cb07', max_length=36),
        ),
    ]
