# Generated by Django 4.2.1 on 2023-05-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_filemodel_alter_subtitledatamodel_subtitleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitledatamodel',
            name='SubtitleID',
            field=models.CharField(default='64351838-f56d-11ed-b839-217e1eb0cb07', max_length=36),
        ),
    ]
