# Generated by Django 4.2.1 on 2023-05-19 12:07

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_subtitledatamodel_subtitleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitledatamodel',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subtitledatamodel',
            name='subtitle_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=apis.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='subtitledatamodel',
            name='SubtitleID',
            field=models.CharField(default='c0a42a84-f63d-11ed-87e4-17a3439d3a11', max_length=36),
        ),
    ]
